# V S S R Rajavarma Ganapathiraju - Assignment - 6

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("bank.csv")

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
dataset.head(10)

age         job   marital  education default  balance housing loan  \
0   59      admin.   married  secondary      no     2343     yes   no   
1   56      admin.   married  secondary      no       45      no   no   
2   41  technician   married  secondary      no     1270     yes   no   
3   55    services   married  secondary      no     2476     yes   no   
4   54      admin.   married   tertiary      no      184      no   no   
5   42  management    single   tertiary      no        0     yes  yes   
6   56  management   married   tertiary      no      830     yes  yes   
7   60     retired  divorced  secondary      no      545     yes   no   
8   37  technician   married  secondary      no        1     yes   no   
9   28    services    single  secondary      no     5090     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may      1042         1     -1         0  unknown     yes  
1  unknown    5   may      1467         1     -1         0  unknown     yes  
2  unknown    5   may      1389         1     -1         0  unknown     yes  
3  unknown    5   may       579         1     -1         0  unknown     yes  
4  unknown    5   may       673         2     -1         0  unknown     yes  
5  unknown    5   may       562         2     -1         0  unknown     yes  
6  unknown    6   may      1201         1     -1         0  unknown     yes  
7  unknown    6   may      1030         1     -1         0  unknown     yes  
8  unknown    6   may       608         1     -1         0  unknown     yes  
9  unknown    6   may      1297         3     -1         0  unknown     yes

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['job'] = le.fit_transform(dataset['job'])
dataset['marital']=le.fit_transform(dataset['marital'])
dataset['education'] = le.fit_transform(dataset['education'])
dataset['default'] = le.fit_transform(dataset['default'])
dataset['housing'] = le.fit_transform(dataset['housing'])
dataset['loan'] = le.fit_transform(dataset['loan'])
dataset['contact'] = le.fit_transform(dataset['contact'])
dataset['month'] = le.fit_transform(dataset['month'])
dataset['poutcome'] = le.fit_transform(dataset['poutcome'])
dataset['deposit'] = le.fit_transform(dataset['deposit'])

In [7]:
dataset['job'].unique()

array([ 0,  9,  7,  4,  5,  1, 10,  2,  3, 11,  6,  8], dtype=int64)

In [8]:
dataset['marital'].unique()

array([1, 2, 0], dtype=int64)

In [9]:
dataset['education'].unique()

array([1, 2, 0, 3], dtype=int64)

In [10]:
dataset['default'].unique()

array([0, 1], dtype=int64)

In [11]:
dataset['housing'].unique()

array([1, 0], dtype=int64)

In [12]:
dataset['loan'].unique()

array([0, 1], dtype=int64)

In [13]:
dataset['contact'].unique()

array([2, 0, 1], dtype=int64)

In [14]:
dataset['month'].unique()

array([ 8,  6,  5,  1, 10,  9,  2,  4,  3,  7,  0, 11], dtype=int64)

In [15]:
dataset['poutcome'].unique()

array([3, 1, 0, 2], dtype=int64)

In [16]:
dataset['deposit'].unique()

array([1, 0], dtype=int64)

In [17]:
x = dataset.iloc[:,0:16].values
y = dataset.iloc[:,16].values

In [18]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()

In [19]:
z1 = one.fit_transform(x[:,1:2]).toarray()
z2 = one.fit_transform(x[:,2:3]).toarray()
z3 = one.fit_transform(x[:,3:4]).toarray()
z4 = one.fit_transform(x[:,8:9]).toarray()
z5 = one.fit_transform(x[:,10:11]).toarray()
z6 = one.fit_transform(x[:,15:16]).toarray()
x = np.delete(x,[1,2,3,8,10,15],axis=1)

C:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before t

In [20]:
x = np.concatenate((z6,z5,z4,z3,z2,z1,x),axis=1)

In [21]:
x.shape

(11162, 48)

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [23]:
x_test.shape

(2233, 48)

In [24]:
y_test.shape

(2233,)

In [25]:
x_train.shape

(8929, 48)

In [26]:
y_train.shape

(8929,)

In [27]:
x_train

array([[ 0.,  0.,  0., ...,  1., -1.,  0.],
       [ 0.,  0.,  0., ...,  1., -1.,  0.],
       [ 0.,  0.,  0., ...,  5., -1.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  8., -1.,  0.],
       [ 0.,  0.,  0., ...,  1., -1.,  0.],
       [ 0.,  0.,  0., ...,  1., -1.,  0.]])

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [29]:
x_train

array([[-0.35031555, -0.22657536, -0.32939951, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.35031555, -0.22657536, -0.32939951, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.35031555, -0.22657536, -0.32939951, ...,  0.92827075,
        -0.48428507, -0.35888264],
       ...,
       [-0.35031555, -0.22657536, -0.32939951, ...,  2.04743488,
        -0.48428507, -0.35888264],
       [-0.35031555, -0.22657536, -0.32939951, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.35031555, -0.22657536, -0.32939951, ..., -0.56394809,
        -0.48428507, -0.35888264]])